### ISSUE TITLE
Using logDebugS family instead of logDebug for logging?

### ISSUE THREAD

**Issue by Javran** [jprupp/json-rpc#9]
I recently discovered this library and one thing that I wish I can do is to filter out logs produced from this library, which tends to overwhelm the logging, which I'm not sure how to do at this moment.

After some research I find that `monad-logger` offers [`filterLogger`](https://hackage.haskell.org/package/monad-logger-0.3.32/docs/Control-Monad-Logger.html#v:filterLogger) that can do this filtering, but that can only be based on a predicate `LogSource -> LogLevel -> Bool`, unfortunately `LogSource` is empty for this library - I'm wondering if this library can switch from using `logDebug` to `logDebugS` (something like `$logDebugS "json-rpc" <log message>`, to be more precise) therefore enhance this filtering ability from user side?

If you are fine with this I'm willing to attempt tackling on this and send a PR if all goes well.

**Comment by jprupp** [comment]
Yes, please do. I'll merge your pull request.
